# If wireguard is running inside LXC container, we should setup kernel module loading
# on host system instead of inside container.
# Put host name inside "lxc_container" group in ansible inventory to mark this.
- import_tasks: kernel-modules.yml
  when: "'wireguard' in group_names and 'lxc_container' not in group_names"

- meta: end_host
  when: "'pve_host' in group_names"

- name: install package on system
  include_tasks: "{{ router_os_distribution }}-pkg.yml"

- name: generate wireguard config
  include_tasks: interface.yml
  loop: "{{ wireguard_interfaces | dict2items }}"
  register: wireguard_conf
  tags:
    - config

- name: deploy resolve dns change script if resolve_dns is defined
  template: src=wireguard-resolve-dns.sh dest=/usr/local/wireguard-resolve-dns.sh
  when: resolve_dns is defined
  tags:
    - config
